name: "Verify uv build"
description: "Verify the uv build artifacts"

author: "Thibaut Durand"

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  package-name:
    description: |
      The name used to install the package. It is also known as distribution name.
      For example, it is the name on PyPI.
    required: true
  module-name:
    description: |
      The name used in import statements. This input is optional and
      the package name is used if no module name is provided.
      The hyphens in the package name will be replaced by underscores.
    required: false
    default: ""
  package-extra:
    description: "The package extra to install"
    required: false
    default: ""
  package-dependencies:
    description: |
      "A list of comma-separated list of required dependencies
      <dependency1>,<dependency2>,<dependency3> ..."
    required: false
    default: ""
  dist-type:
    description: "The distribution artifact. Choose either wheel or sdist"
    required: false
    default: "wheel"
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    # Step 1: Validate dist-type input
    - name: Verify dist-type
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${{ inputs.dist-type }}" != "wheel" && "${{ inputs.dist-type }}" != "sdist" ]]; then
          echo "❌ Error: input 'dist-type' must be 'wheel' or 'sdist'."
          exit 1
        fi
        echo "✅ Distribution type: ${{ inputs.dist-type }}"

    # Step 2: Install uv package manager
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true

    # Step 3: Build the package
    - name: Build package
      shell: bash
      run: |
        set -euo pipefail
        echo "📦 Building package..."
        uv build
        echo "✅ Build completed"

    - name: Find wheel path
      shell: bash
      run: |
        WHEEL_PATH=$(ls dist/*.whl | head -n1)

        if [ -z "$WHEEL_PATH" ]; then
          echo "❌ Error: No wheel distribution found"
          exit 1
        fi

        echo "📄 Found wheel file: $WHEEL_PATH"
        echo "WHEEL_PATH=$WHEEL_PATH" >> $GITHUB_ENV

    - name: Find sdist path
      shell: bash
      run: |
        SDIST_PATH=$(ls dist/*.tar.gz | head -n1)

        if [ -z "$SDIST_PATH" ]; then
          echo "❌ Error: No sdist distribution found"
          exit 1
        fi

        echo "📄 Found sdist file: $SDIST_PATH"
        echo "SDIST_PATH=$SDIST_PATH" >> $GITHUB_ENV

    # Step 4: Choose the target distribution file
    - name: Choose target distribution
      shell: bash
      id: dist
      run: |
        set -euo pipefail
        if [ "${{ inputs.dist-type }}" = "wheel" ]; then
          TARGET=$WHEEL_PATH
        else
          TARGET=$SDIST_PATH
        fi

        if [ -z "$TARGET" ]; then
          echo "❌ Error: No ${{ inputs.dist-type }} distribution found"
          exit 1
        fi

        echo "📄 Found distribution: $TARGET"
        echo "target=$TARGET" >> "$GITHUB_OUTPUT"

    # Step 5: Verify py.typed marker exists
    - name: Check py.typed in distribution
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ inputs.dist-type }}" = "wheel" ]; then
          TOOL="unzip -l"
        else
          TOOL="tar -tzf"
        fi

        output=$($TOOL "${{ steps.dist.outputs.target }}")
        if echo "$output" | grep -q py.typed; then
          echo "✅ py.typed marker found"
        else
          echo "❌ Error: py.typed marker not found"
          exit 1
        fi

    - name: Verify extra is defined in wheel metadata
      shell: bash
      run: |
        echo "🔍 Verifying extra is defined in wheel metadata..."
        bash $GITHUB_ACTION_PATH/scripts/verify_wheel_extras.sh $WHEEL_PATH ${{ inputs.package-extra }}
        echo "✅ wheel extra checks passed"

    # Step 6: Install the built package
    - name: Install built package
      shell: bash
      run: |
        set -euo pipefail
        PKG="${{ steps.dist.outputs.target }}"
        if [ -n "${{ inputs.package-extra }}" ]; then
          PKG="${PKG}[${{ inputs.package-extra }}]"
          echo "📦 Installing package with extra: ${{ inputs.package-extra }}"
        else
          echo "📦 Installing package..."
        fi
        uv pip install "$PKG"
        echo "✅ Package installed successfully"

    # Step 7: Validate package metadata with twine
    - name: Install and run twine check
      shell: bash
      run: |
        set -euo pipefail
        if uv pip install twine 2>/dev/null; then
          echo "🔍 Running twine check..."
          twine check dist/*
          echo "✅ Twine check passed"
        else
          echo "⚠️  Twine not available, skipping metadata validation"
        fi

    # Step 8: Run custom metadata checks
    - name: Check package metadata
      shell: bash
      run: |
        set -euo pipefail
        echo "🔍 Checking package metadata..."
        bash $GITHUB_ACTION_PATH/scripts/check_metadata.sh ${{ inputs.package-name }} ${{ inputs.package-dependencies }}
        echo "✅ Metadata checks passed"

    # Step 9: Verify dependency tree
    - name: Check dependency tree
      shell: bash
      run: |
        set -euo pipefail
        echo "🔍 Checking dependency tree..."
        bash $GITHUB_ACTION_PATH/scripts/check_dependency_tree.sh ${{ inputs.package-name }} ${{ inputs.package-dependencies }}
        echo "✅ Dependency tree checks passed"

    - name: Find module name
      shell: bash
      run: |
        MODULE_NAME=${{ inputs.module-name }}
        if [ -z "$MODULE_NAME" ]; then
          PACKAGE_NAME=${{ inputs.package-name }}
          MODULE_NAME="${PACKAGE_NAME//-/_}"
        fi
        echo "MODULE_NAME=$MODULE_NAME"
        echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV

    # Step 10: Test package import and version
    - name: Verify package import and version
      shell: bash
      run: |
        set -euo pipefail
        echo "🔍 Testing package import..."

        VERSION=$(python -c "import $MODULE_NAME; print($MODULE_NAME.__version__)")
        echo "📌 Package version: $VERSION"

        if [ "$VERSION" = "0.0.0" ]; then
          echo "❌ Error: Package version is placeholder '0.0.0'"
          exit 1
        fi

        echo "✅ Package imported successfully with valid version"

    # Step 11: Validate type hints
    - name: Check package type hints
      shell: bash
      run: |
        set -euo pipefail
        if uv pip install pyright 2>/dev/null; then
          echo "🔍 Running type hint validation..."
          $GITHUB_ACTION_PATH/scripts/check_type.sh $MODULE_NAME
        else
          echo "⚠️  Pyright not available, skipping type check"
        fi

    - name: Show artifacts
      shell: bash
      if: always()
      run: |
        set -euo pipefail
        echo "🔍 Show wheel content"
        unzip -l $(ls dist/*.whl | head -n1)
        echo ""
        echo "🔍 Show sdist content"
        tar -tzf $(ls dist/*.tar.gz | head -n1)
