name: Format
on:
  workflow_call:
  workflow_dispatch: # to trigger manually

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          echo "📦 Installing all dependencies..."
          npm install -g markdownlint-cli
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
          sudo snap install shfmt

      - name: Run markdownlint
        run: |
          echo "📝 Running markdownlint..."
          markdownlint -- **/*.md

      - name: Run ShellCheck
        run: |
          echo "🐚 Running ShellCheck..."
          shellcheck -- **/*.sh || exit 1

      - name: Run shfmt
        run: |
          echo "✨ Checking formatting using shfmt..."
          shfmt -d -- **/*.sh

      - name: Run yamllint
        run: |
          echo "🔍 Running yamllint..."
          yamllint -f colored .
